description: [A free, open-access programme of study on generative AI for academics.]
name: Generative AI for academics
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one