title: Generative AI for academics
description: A free, open-access programme of study on AI in higher education.
remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one