title: AI in HPE
description: An open-source, open-access resource on generative AI in health professions education.
url: "https://michael-rowe.github.io"
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-sitemap
- jekyll-feed
google_analytics: G-55NH3EFXFQ